//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmarStory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharDialog
    {
        public int Id { get; set; }
        public int CharId { get; set; }
        public string Text { get; set; }
        public string Result { get; set; }
        public string Condition { get; set; }
    }
}
